default: &default
  adapter: mysql2
  encoding: utf8 

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: furima_28297_development
test:
  <<: *default
  database: furima_28297_test
production:
  <<: *default
  database: furima_28297_production
  username: furima_28297
  password: <%= ENV['FURIMA_28297_DATABASE_PASSWORD'] %>
